// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0d8XPYBwntyuDim3PXFIrPvA_pug0lOQ',
    appId: '1:471132446155:web:48e83c498316973f716a4e',
    messagingSenderId: '471132446155',
    projectId: 'pasy-b0213',
    authDomain: 'pasy-b0213.firebaseapp.com',
    storageBucket: 'pasy-b0213.firebasestorage.app',
    measurementId: 'G-XR45RP1D1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAjRzgdg6z78NxWj75QXR-QaDU5Eeds7A',
    appId: '1:471132446155:android:1ec1de0a5ad34110716a4e',
    messagingSenderId: '471132446155',
    projectId: 'pasy-b0213',
    storageBucket: 'pasy-b0213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBk14FFBC3j6WknvWjUA-dOD3FuRBG-7E',
    appId: '1:471132446155:ios:daa5c7db8e44c961716a4e',
    messagingSenderId: '471132446155',
    projectId: 'pasy-b0213',
    storageBucket: 'pasy-b0213.firebasestorage.app',
    iosBundleId: 'com.example.pasAppFresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBk14FFBC3j6WknvWjUA-dOD3FuRBG-7E',
    appId: '1:471132446155:ios:daa5c7db8e44c961716a4e',
    messagingSenderId: '471132446155',
    projectId: 'pasy-b0213',
    storageBucket: 'pasy-b0213.firebasestorage.app',
    iosBundleId: 'com.example.pasAppFresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0d8XPYBwntyuDim3PXFIrPvA_pug0lOQ',
    appId: '1:471132446155:web:d85b264dab06aaa0716a4e',
    messagingSenderId: '471132446155',
    projectId: 'pasy-b0213',
    authDomain: 'pasy-b0213.firebaseapp.com',
    storageBucket: 'pasy-b0213.firebasestorage.app',
    measurementId: 'G-GTZ5K7ZHPW',
  );

}